default: &default
  adapter: <%= ENV.fetch('DATABASE_ADAPTER', 'postgresql') %>

development:
  <<: *default
  database: db/demo_mode_development.sqlite

test:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', 'postgresql://127.0.0.1/demo_mode_test') %>
